# 1.이미지 입출력 
## 이미지표시
- https://www.pexels.com/ko-kr/ 에서 고양이 무료 이미지 다운로드

#### <span style="color:blue"> imread() - 파일 읽기 함수

- `image = cv2.imread(fileName[, flags])`->retval
    - fileName:읽어올 파일명
    - flags : 이미지를 초기에 불러올 때 적용할 초기 상태를 의미합니다.
        - cv2.IMREAD_UNCHANGED : 원본 사용(-1), alpha channel까지 포함해읽음(png파일)
        - cv2.IMREAD_GRAYSCALE : 그레이스케일로 읽음(0), 1 채널, 실제 이미지 처리시 중간단계로 많이 사용한다.
        - cv2.IMREAD_COLOR : COLOR로 읽음(1) , 3 채널, 투명한 부분은 무시되며, flag디폴트 값이다.


#### <span style="color:blue"> imshow() 화면 표시 함수
- 이미지 배열을 창(window)에 표시하며, 창 이름과 이미지 데이터를 인수로 받음
- 이미지를 출력한 후에는 반드시 cv2.waitKey로 사용자 입력을 기다리거나, 창이 유지되어야 함함
- `cv2.imshow(Title, imageObject)`
    - Title (Required): 이미지를 보여주는 Window 창의 이름임.
    - imageObject (Required): 이미지 객체행렬로 cv2.imread()의 반환값을 입력하면 됨.
- Google Colab에서는 cv2_imshow() 사용

In [1]:
import cv2

img_file = '../cv_images/img.jpg'
img = cv2.imread(img_file)         # ... 코드 입력              # 이미지 파일을 메모리에 읽기
cv2.imshow('img', img)         # ... 코드 입력                    # 해당 이미지 표시

cv2.waitKey(0)                            # 아무키나 누르면 이미지 표시창이 종료됩니다.
cv2.destroyAllWindows()

### 이미지 읽어 보여주기 - 기본모드

In [6]:
# 방법1
import cv2
img_file = '../cv_images/img.jpg'
img = cv2.imread(img_file)   # 해당 경로의 파일 읽어오기

cv2.imshow('img', img)       # img 라는 이름의 창에 img를 표시

cv2.waitKey(0)               # 지정된 시간동안 사용자 키 입력대기 , 0-무한정
cv2.destroyAllWindows()      # 모든 창 닫기

In [10]:
# 방법2
img_file = '../cv_images/img.jpg'
img = cv2.imread(img_file)    # 이미지를 읽어서 img 변수에 할당 

if img is not None:
    cv2.imshow('IMG', img)      # 읽은 이미지를 화면에 표시     
    cv2.waitKey(0)               # 키가 입력될 때 까지 대기      
    cv2.destroyAllWindows()     # 창 모두 닫기            
else:
    print('No image file.')

### 이미지 읽어 보여주기1 - 3가지 모드

In [ ]:
import cv2
img_file = '../cv_images/img.jpg'

img_color = cv2.imread(img_file, cv2.IMREAD_COLOR) # ... 코드 입력    # 컬러 이미지로 읽기
img_gray  = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE) # ... 코드 입력     # 흑백 이미지로 읽기
img_unchanged = cv2.imread(img_file, cv2.IMREAD_UNCHANGED) # ... 코드 입력 # 원본 이미지 그대로 읽기

cv2.imshow('img_color', img_color)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_unchanged', img_unchanged)

cv2.waitKey(0)
cv2.destroyAllWindows()

## 이미지 파일 저장

#### <font color=blue> @khs - imwrite()
- cv2.imwrite(filename, img[,params]) -> retval 

In [12]:
import cv2
img_file = '../cv_images/img.jpg'
save_file = './img_gray.jpg'
save_file1 = './img_gray.png'

img = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)
cv2.imshow(img_file, img)

cv2.imwrite(save_file, img) #파일로 저장, 포맷은 확장에 따름
cv2.imwrite(save_file1, img)  # png 형태로 저장

cv2.waitKey(0)
cv2.destroyAllWindows()

##  이미지이해
- shape : 이미지의 height, width, channel 정보 - 저장된 이미지의 Numpy 배열 크기(높이, 너비, 채널)

```python
img = [
        [ [B,G,R], [B,G,R], [B,G,R], ..., [B,G,R] ],  ← img[0]: 첫 번째 행 (y = 0)
        [ [B,G,R], [B,G,R], [B,G,R], ..., [B,G,R] ],  ← img[1]: 두 번째 행 (y = 1)
        ...
        [ ... ]                                        ← img[389]: 마지막 행
]
```

In [13]:
import cv2
img_file = '../cv_images/img.jpg'
img = cv2.imread(img_file)
print(img.shape) 

print(img[0])
print(img[0].shape)

(390, 640, 3)
[[  4  45  38]
 [ 21  62  55]
 [ 19  57  51]
 ...
 [ 52 162 158]
 [ 52 162 158]
 [ 52 162 158]]
(640, 3)


In [7]:
# 첫 번째 행의 첫 번째 픽셀 값 출력
print(img[0][0])  # 예: [255, 0, 0] (BGR 순서로 파란색)

# 첫 번째 행의 두 번째 픽셀 값
print(img[0][1])  # 예: [0, 255, 0] (초록색)

[ 4 45 38]
[21 62 55]


In [8]:

# 첫 번째 행의 첫 번째 픽셀 값 출력
print(img[0][0][0])  # 예: [255, 0, 0] (BGR 순서로 파란색)

# 첫 번째 행의 두 번째 픽셀 값
print(img[0][1][1])  # 예: [0, 255, 0] (초록색)

4
62


- 그레이 스케일로 읽을 때
```python
img_gray =
[
  [  52,  60,  74,  90,  80 ],  ← img_gray[0]
  [  50,  61,  73,  88,  79 ],
  [  49,  58,  70,  85,  76 ],
  [  47,  55,  67,  82,  73 ]
]
```

In [23]:
img_gray = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE) # 이미지를 그레이 스케일로 읽기
print(img_gray[0])

[ 38  55  51  33  30  30  24  22  36  39  31  29  40  44  41  43  40  41
  39  35  39  49  53  50  50  42  31  20  13  21  49  75  82 103 112  84
  59  77 106 111 107  81  68  66  61  59  60  54  72  96 108  98  95 112
 129 135 122 109 100 100  96  89  91 100 106 113  94 102 113 110 106  71
  82  90  91  82  74  71  64  55  65  68  78  98 121 127 109  86  67  58
  58  68  73  68  64  64  64  60  44  36  48  57  59  65  73  75  83  94
  97  99 108 119 116 113 111 110 110 110 109 108 110 113 116 115 110 104
 101  99 100  94  94  99  96  90  96 109 108 109 107 105 106 105  96  86
  85  78  84 102 112 108 111 121 115 111 102  95  99 108 110 105 111 114
 117 118 116 115 114 114 123 127 133 136 137 140 145 149 146 139 132 130
 130 123 109  97  90  81  73  72  73  72  72  74  75  72  69  68  68  68
  66  64  67  66  69  75  79  81  87  94 103 104 110 119 131 139 141 141
 138 137 137 139 142 143 141 137 133 132 130 127 124 121 119 118 120 122
 125 128 131 133 133 133 136 141 144 145 148 154 15

## 온라인에 있는 이미지 파일 읽기
- JPEG 바이트 (압축된 데이터) → [bytearray] → cv2.imdecode() → 3차원 배열 (H x W x 3)

In [14]:
from urllib import request
import numpy as np
import cv2

# 이미지 URL 지정 (OpenCV 로고 이미지)
#url = "https://upload.wikimedia.org/wikipedia/ko/thumb/2/24/Lenna.png/220px-Lenna.png"
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/OpenCV_Logo_with_text_svg_version.svg/800px-OpenCV_Logo_with_text_svg_version.svg.png"
#url1 = 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.scientificamerican.com%2Farticle%2Fhow-house-cats-evolved%2F&psig=AOvVaw3rOHKuZUI2v9S4D_2CZI6z&ust=1745653151369000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCLjOsPHW8owDFQAAAAAdAAAAABAE'
# URL에서 이미지 데이터를 읽어오기 (바이트 형태로 가져옴)
source = request.urlopen(url).read()          # source = b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR...'  # PNG 파일의 원시 데이터 (Byte 형태)
 
# 바이트 데이터를 numpy 배열로 변환 (uint8 타입)
image = np.array(bytearray(source), dtype=np.uint8)
print("변환 전 이미지 shape = ", image.shape)  # 아직 디코딩 전

# 이미지 디코딩 (컬러 이미지로 읽음)
image = cv2.imdecode(image, cv2.IMREAD_COLOR)
print("디코딩 후 이미지 shape = ", image.shape)

# 이미지 저장
cv2.imwrite("test_download.png", image)

# 한글 제목의 창 생성 (크기 조절 가능)
cv2.namedWindow("한글", cv2.WINDOW_NORMAL)

# 이미지 출력
cv2.imshow("한글", image)

# 'q' 키를 누를 때까지 대기
while True:
    key = cv2.waitKey()
    if key == ord('q'):
        break

# 모든 OpenCV 창 닫기
cv2.destroyAllWindows()


변환 전 이미지 shape =  (47049,)
디코딩 후 이미지 shape =  (986, 800, 3)


## 디렉토리 내 이미지읽기

In [15]:
import os

# "../cv_images" 폴더 안의 파일 목록을 가져오기
img_list = os.listdir('../cv_images')           # ... 코드 입력

# 유효한 이미지 파일들의 경로를 저장할 리스트
img_files = []

# 허용할 이미지 파일 확장자 집합 정의 : .png, .jpg, .jpeg 대상
valid_extensions = {'.png', '.jpg', '.jpeg'}          # ... 코드 입력

# 폴더 내의 각 파일(img_list)에 대해 반복
for i in img_list :        # ... 코드 입력
    
    # 경로에서 문자단위로 split한 후 파일의 확장자를 소문자로 바꿔서 유효한 확장자인지 확인
    if os.path.splitext(i)[1] in valid_extensions:   # ... 코드 입력
        # 전체 이미지 경로 구성
        img_dir = "../cv_images/" + i
        # 유효한 이미지 파일 리스트에 추가
        img_files.append(img_dir)           # ... 코드 입력

# 최종적으로 유효한 이미지 파일 목록을 출력
display(img_files)

['../cv_images/apple1.png',
 '../cv_images/apple2.png',
 '../cv_images/apple3.png',
 '../cv_images/apple4.png',
 '../cv_images/background.jpg',
 '../cv_images/banana.jpg',
 '../cv_images/bicycle.jpg',
 '../cv_images/bird.jpg',
 '../cv_images/blur.png',
 '../cv_images/book.jpg',
 '../cv_images/bricks.jpeg',
 '../cv_images/bright.jpg',
 '../cv_images/card.png',
 '../cv_images/card_crop_1.png',
 '../cv_images/card_crop_2.png',
 '../cv_images/card_crop_3.png',
 '../cv_images/card_crop_4.png',
 '../cv_images/cat (1).jpg',
 '../cv_images/cat.jpg',
 '../cv_images/change.png',
 '../cv_images/city.png',
 '../cv_images/cmap.png',
 '../cv_images/cropland.png',
 '../cv_images/dark.png',
 '../cv_images/dilate.png',
 '../cv_images/dog.jpg',
 '../cv_images/dog2.jpg',
 '../cv_images/dog_backpack.png',
 '../cv_images/drawing1.jpg',
 '../cv_images/drawing2.jpg',
 '../cv_images/erode.png',
 '../cv_images/face.jpg',
 '../cv_images/fish.jpg',
 '../cv_images/fish.png',
 '../cv_images/flower.jpg',
 '../cv_im