# QR 코드 생성하기

## 1.qrcode 모듈 설치
- https://pypi.org/project/qrcode/

In [2]:
!pip install qrcode pillow

## 2.관련 모듈 가져오기

In [3]:
import qrcode

## 3.QR 코드 생성

In [4]:
qr_data = 'https://www.kccistc.net/'
qr_img = qrcode.make(qr_data)

save_path = 'kccistc' + '.png'
qr_img.save(save_path)

## 4.QR코드 생성 목록 텍스트 파일 읽어 오기

In [ ]:
# 'qr_코드모음.txt' 파일 다운로드하기
#!gdown 1v9yQUOBU_E8_N4jI4lMQM7oH3VlF2K8a

In [7]:
file_list = 'qr코드모음.txt'

# 코드 작성 : file_list 를 읽어서 각 행을 출력합니다.
with open(file_list, 'r', encoding='utf-8') as f :
    read_lines = f.readlines()
    for line in read_lines:
        line = line.strip()
        qr_img = qrcode.make(line)
        
        save_path = line + '.png'
        qr_img.save(save_path)

## 5.텍스트 파일 읽어서 QR코드 생성

In [ ]:
# 코드 작성 : 4번 단계에서 파일에서 읽은 각 라인의 URL 주소를 읽어 QR코드를 생성합니다.(4번단계에 3번단계 추가)










# QR 읽어 정보 가져오기

## 1.관련 모듈 설치하기

In [8]:
# colab 에서 decoding 을 위한 zbar 공유 라이브러리
#!apt-get install libzbar0  #  QR 코드를 디코딩하기 위해 필수적으로 사용하는 zbar 공유 라이브러리

# window 에서 https://www.microsoft.com/ko-KR/download/details.aspx?id=40784 에서 OS 에 따른 파일 다운받아 설치
#            (windows :vcredist_x64.exe)
# QR / Bar 코드 인식
!pip install pyzbar     

!pip install opencv-python
!pip install requests
!pip install beautifulsoup4

   ---------------------------------------- 0.0/817.4 kB ? eta -:--:--
   -------------------------------------- - 786.4/817.4 kB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 817.4/817.4 kB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/39.5 MB ? eta -:--:--
    --------------------------------------- 0.8/39.5 MB 4.2 MB/s eta 0:00:10
   - -------------------------------------- 1.3/39.5 MB 3.0 MB/s eta 0:00:13
   - -------------------------------------- 1.3/39.5 MB 3.0 MB/s eta 0:00:13
   - -------------------------------------- 1.8/39.5 MB 2.2 MB/s eta 0:00:17
   -- ------------------------------------- 2.4/39.5 MB 2.3 MB/s eta 0:00:17
   -- ------------------------------------- 2.9/39.5 MB 2.4 MB/s eta 0:00:16
   --- ------------------------------------ 3.1/39.5 MB 2.1 MB/s eta 0:00:18
   --- ------------------------------------ 3.4/39.5 MB 2.1 MB/s eta 0:00:18
   --- ------------------------------------ 3.4/39.5 MB 2.1 MB/s eta 0:00:18
   ---

## 2.qr 코드 읽어 디코딩하기

In [ ]:
import cv2
from pyzbar.pyzbar import decode

# 이미지 읽기
image = cv2.imread("kccistc.png")   # numpy의 배열로 저장됨!

print(image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [11]:
import cv2
from pyzbar.pyzbar import decode

# 이미지 읽기
image = cv2.imread("kccistc.png")

# QR 코드 디코딩
barcodes = decode(image)

# 디코딩 결과 출력
if barcodes:
    for barcode in barcodes:
        print("QR Code: ", barcode.data.decode("utf-8"))  # 출력: We_Great
else:
    print("QR 코드를 찾지 못했습니다.")

QR Code:  https://www.kccistc.net/


## 3.qr 코드를 읽어 해당 웹사이트의 정보 가져오기

In [20]:
import cv2
from pyzbar.pyzbar import decode
import requests
from bs4 import BeautifulSoup

# 이미지 읽기
image = cv2.imread("kccistc.png")

# QR 코드 디코딩
barcodes = decode(image)

# 디코딩 결과 출력
if barcodes:
    for barcode in barcodes:
        qr_link = barcode.data.decode('utf-8')  # QR 코드에서 URL 추출
        print("QR Code Link:", qr_link)
        try:
            # User-Agent 헤더 추가
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0 Safari/537.36'
            }
            response = requests.get(qr_link, headers=headers)  # 웹 요청
            print("Status Code:", response.status_code)
            soup = BeautifulSoup(response.text, 'html.parser')  # HTML 파싱

            # 강좌 제목 추출
            titles = soup.find_all("div", class_="title")
            if titles:
                print("Titles found on the page:")
                for idx, title_div in enumerate(titles, 1):
                    title_text = title_div.get_text(strip=True)
                    print(f"{idx}. {title_text}")
            else:
                print("No course titles found on the page.")
        except requests.RequestException as e:
            print("Error fetching QR Code content:", e)
else:
    print("QR 코드를 찾지 못했습니다.")

QR Code Link: https://www.kccistc.net/
Status Code: 200
Titles found on the page:
1. [Intel] 엣지 AI SW 아카데미(8기)
2. [취업 최우수과정][Intel] 엣지 AI SW 아카데미(8기)
3. [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어(2기)
4. [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어(2기)
5. [Intel]엣지 AI SW아카데미(7기)
6. [Intel]엣지 AI SW아카데미(7기)
7. AI 시스템반도체 설계(2기)
8. [한국팹리스산업협회,넥스트칩]AI 시스템반도체 설계(2기)
9. 반도체장비 제어 전문가
10. [취업요청 최다과정]반도체장비 제어 전문가[PLC,영상비전제어]
11. AI시스템반도체 SW 개발자
12. [Telechips]AI시스템반도체 SW 개발자
13. [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어
14. [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어
15. [Intel] 엣지 AI SW 아카데미(6기)
16. [취업우수과정][Intel] 엣지 AI SW 아카데미(6기)
17. [에이텍 맞춤과정] 인공지능을 활용한 업무효율화
18. [에이텍 맞춤과정] 인공지능을 활용한 업무효율화
19. 미디어파사드 영상콘텐츠 제작
20. 미디어파사드 영상콘텐츠 제작
21. [에이텍 맞춤과정] 기술과 품질을 위한 전략 실무
22. [에이텍 맞춤과정] 기술과 품질을 위한 전략 실무
23. 프로젝션 맵핑 및 매드맵퍼 활용
24. 프로젝션 맵핑 및 매드맵퍼 활용
25. [투비소프트 맞춤과정] 디지털 전환을 위한 UI/UX 플랫폼 기본 컴포넌트 활용[25년]
26. [투비소프트 맞춤과정] 디지털 전환을 위한 UI/UX 플랫폼 기본 컴포넌트 활용[25년]
27. [투비소프트 맞춤과정] UI/UX 플랫폼을 활용한 사례중심 실무 활용[25년]
28. [투비소프트 맞춤과정] UI/UX 플랫폼을 활용한 사례중심 

In [21]:
import cv2
from pyzbar.pyzbar import decode
import requests
from bs4 import BeautifulSoup

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0 Safari/537.36'
}
response = requests.get('https://www.kccistc.net/', headers=headers)  # 웹 요청
print("Status Code:", response.status_code)
print(response)
soup = BeautifulSoup(response.text, 'html.parser')  # HTML 파싱
soup

Status Code: 200
<Response [200]>



<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="ko" xml:lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="대한상공회의소 7개 인력개발원, 기술인력 양성 및 취업, 교육훈련 안내, 입학정보, 취업 및 구인 정보, 국비지원교육, 전문기술 교육" name="description"/>
<meta content="대한상공회의소 7개 인력개발원, 기술인력 양성 및 취업, 교육훈련 안내, 입학정보, 취업 및 구인 정보, 국비지원교육, 전문기술 교육" name="og:description"/>
<meta content="서울기술교육센터" name="subject">
<meta content="서울기술교육센터" name="title">
<meta content="서울기술교육센터" name="author">
<meta content="서울기술교육센터" name="keywords">
<meta content="https://www.kccistc.net:443/index.jsp" property="og:url">
<title>서울기술교육센터</title>
<link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/css/main24/common.css" rel="stylesheet" type="text/css"/>
<link href=

In [22]:
# category, title 추출하기
import cv2
from pyzbar.pyzbar import decode
import requests
from bs4 import BeautifulSoup

# 이미지 읽기
image = cv2.imread("kccistc.png")

# QR 코드 디코딩
barcodes = decode(image)

# 디코딩 결과 출력
if barcodes:
    for barcode in barcodes:
        qr_link = barcode.data.decode('utf-8')  # QR 코드에서 URL 추출
        print("QR Code Link:", qr_link)
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0 Safari/537.36'
            }
            response = requests.get(qr_link, headers=headers)
            print("Status Code:", response.status_code)
            soup = BeautifulSoup(response.text, 'html.parser')

            # 모든 contents_box를 찾기
            content_boxes = soup.find_all("div", class_="contents_box")
            if content_boxes:
                print("Category & Title found in each contents_box:")
                for idx, box in enumerate(content_boxes, 1):
                    category = box.find("div", class_="category")
                    title = box.find("div", class_="title")

                    category_text = category.get_text(strip=True) if category else "No category"
                    title_text = title.get_text(strip=True) if title else "No title"

                    print(f"{idx}. [{category_text}] {title_text}")
            else:
                print("No contents_box found on the page.")
        except requests.RequestException as e:
            print("Error fetching QR Code content:", e)
else:
    print("QR 코드를 찾지 못했습니다.")

QR Code Link: https://www.kccistc.net/
Status Code: 200
Category & Title found in each contents_box:
1. [#인텔현업엔지니어직강 #임베디드] [취업 최우수과정][Intel] 엣지 AI SW 아카데미(8기)
2. [#K- Digital Training] [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어(2기)
3. [#인텔현업엔지니어직강 #임베디드] [Intel]엣지 AI SW아카데미(7기)
4. [#KDT #반도체설계] [한국팹리스산업협회,넥스트칩]AI 시스템반도체 설계(2기)
5. [#내일배움카드발급무관 #PLC] [취업요청 최다과정]반도체장비 제어 전문가[PLC,영상비전제어]
6. [#내일배움카드발급무관 #임베디드] [Telechips]AI시스템반도체 SW 개발자
7. [#K- Digital Training] [HARMAN] 세미콘아카데미-시스템반도체 설계/검증 엔지니어
8. [#인텔현업엔지니어직강 #임베디드] [취업우수과정][Intel] 엣지 AI SW 아카데미(6기)
9. [#IT.정보통신 #주간] [에이텍 맞춤과정] 인공지능을 활용한 업무효율화
10. [#IT.정보통신 #주말] 미디어파사드 영상콘텐츠 제작
11. [#IT.정보통신 #주간] [에이텍 맞춤과정] 기술과 품질을 위한 전략 실무
12. [#IT.정보통신 #주말] 프로젝션 맵핑 및 매드맵퍼 활용
13. [#IT.정보통신 #주간] [투비소프트 맞춤과정] 디지털 전환을 위한 UI/UX 플랫폼 기본 컴포넌트 활용[25년]
14. [#IT.정보통신 #주간] [투비소프트 맞춤과정] UI/UX 플랫폼을 활용한 사례중심 실무 활용[25년]
15. [#전기전자 #주간] SoC 반도체 설계
16. [#전기전자 #주간] 반도체 System Verilog 실무
17. [#전기전자 #주간] SoC 반도체 검증
18. [#전기전자 #주간] SoC 반도체 검증
19. [#전기전자 #주간] SoC 반도체 설계
20. [#IT.정